# Generated by Django 5.1.7 on 2025-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(default='#f1f1f1', max_length=20),
        ),
    ]
