# Generated by Django 5.1.7 on 2025-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_column_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
