# Generated by Django 5.1.7 on 2025-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_card_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='#f1f1f1', max_length=20),
        ),
    ]
