# Generated by Django 5.1.7 on 2025-06-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_aichatmessage'),
    ]

    operations = [
    ]
