# Generated by Django 5.1.7 on 2025-06-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_cardattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Swimlane', max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=300)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimlanes', to='frontend.board')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='swimlane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='frontend.swimlane'),
        ),
    ]
