# Generated by Django 5.1.7 on 2025-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_swimlane_card_swimlane'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='email_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
