# Generated by Django 5.1.7 on 2025-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_card_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='email_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
