# Generated by Django 5.1.7 on 2025-07-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_card_email_id'),
        ('frontend', '0011_add_email_id_manual'),
    ]

    operations = [
    ]
