# Generated by Django 5.1.5 on 2025-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_merge_20250702_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board_images/'),
        ),
    ]
