# Generated by Django 5.1.5 on 2025-08-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, help_text='Board image (JPEG, PNG, GIF, WebP - Max 5MB)', null=True, upload_to='board_images/'),
        ),
    ]
