# Generated by Django 5.1.5 on 2025-08-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='css_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
