# Generated by Django 5.1.5 on 2025-08-19 11:08

from django.db import migrations


def populate_css_classes(apps, schema_editor):
    """Populate CSS classes for existing cards based on their colors"""
    Card = apps.get_model('frontend', 'Card')
    
    COLOR_CSS_MAP = {
        'rgb(241, 11, 11)': 'card-color-red',
        'rgb(247, 103, 7)': 'card-color-orange',
        'rgb(247, 243, 11)': 'card-color-yellow',
        'rgb(165, 231, 9)': 'card-color-light-green',
        'rgb(12, 133, 8)': 'card-color-dark-green',
        'rgb(13, 160, 111)': 'card-color-teal',
        'rgb(20, 197, 159)': 'card-color-cyan',
        'rgb(15, 41, 161)': 'card-color-blue',
        'rgb(118, 11, 240)': 'card-color-purple',
        'rgb(194, 8, 178)': 'card-color-magenta',
        'rgb(230, 20, 90)': 'card-color-pink',
        'rgb(2, 9, 15)': 'card-color-dark'
    }
    
    updated_count = 0
    for card in Card.objects.all():
        if card.color and not card.css_class:
            css_class = COLOR_CSS_MAP.get(card.color)
            if css_class:
                card.css_class = css_class
                card.save()
                updated_count += 1
    
    print(f"Updated {updated_count} cards with CSS classes")


def reverse_populate_css_classes(apps, schema_editor):
    """Remove CSS classes from cards (reverse operation)"""
    Card = apps.get_model('frontend', 'Card')
    Card.objects.update(css_class=None)


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_card_css_class'),
    ]

    operations = [
        migrations.RunPython(populate_css_classes, reverse_populate_css_classes),
    ]
