# Generated by Django 5.1.5 on 2025-08-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20250819_1208'),
    ]

    operations = [
    ]
