# Generated by Django 5.1.5 on 2025-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_userprofile_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marketing_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_format',
            field=models.CharField(choices=[('12', '12-hour (AM/PM)'), ('24', '24-hour')], default='12', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
