# Generated by Django 5.1.5 on 2025-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_twofactorcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_format',
            field=models.CharField(default='24-hour', max_length=20),
        ),
        migrations.DeleteModel(
            name='TwoFactorCode',
        ),
    ]
