# Generated by Django 5.1.5 on 2026-01-10 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='message',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(64000)]),
        ),
        migrations.AlterField(
            model_name='aichatmessage',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='question',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(64000)]),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='response',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(64000)]),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, help_text='Board image (JPEG, PNG, GIF, WebP - Max 5MB)', max_length=255, null=True, upload_to='board_images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(16000)]),
        ),
        migrations.AlterField(
            model_name='cardattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to='card_attachments/'),
        ),
        migrations.AlterField(
            model_name='cardattachment',
            name='file_type',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='cardlogentry',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='column',
            name='color',
            field=models.CharField(default='#f1f1f1', max_length=32),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(64000)]),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
