# Generated by Django 5.1.5 on 2026-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_userprofile_plan_userprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_monthly_token_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_usage_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
