# Generated by Django 5.1.5 on 2026-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_userprofile_monthly_tokens_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_tokens_used',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_monthly_token_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='token_usage_reset_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_api_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(blank=True, choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (ChatGPT)'), ('google', 'Google (Gemini)'), ('mistral', 'Mistral AI'), ('deepseek', 'DeepSeek')], max_length=20, null=True),
        ),
    ]
