# Generated by Django 5.1.5 on 2026-03-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_remove_userprofile_monthly_tokens_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
