# Generated by Django 5.1.5 on 2026-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_userprofile_ai_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
