# Generated by Django 5.1.5 on 2026-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_remove_email_id_and_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ai_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='ai_context_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
