# Generated by Django 5.1.5 on 2026-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_credit_based_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_chat_always_open',
            field=models.BooleanField(default=False),
        ),
    ]
