# Generated by Django 5.1.5 on 2026-06-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_migrate_messages_to_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_credits_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_credits_used_this_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_questions_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_questions_today',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_tokens_today',
        ),
    ]
